# puppet-agent container container

FROM amazonlinux:latest

RUN yum update -y
RUN yum upgrade -y
RUN rpm -Uvh https://yum.puppet.com/puppet7/puppet7-release-el-7.noarch.rpm
RUN yum install puppetserver.noarch -y
RUN yum install puppet-agent

ENV PATH=/opt/puppetlabs/bin:$PATH

# need to figure out how to keep this container running
#CMD ["vi"]