FROM ubuntu

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install wget -y
RUN wget https://golang.org/dl/go1.17.2.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.17.2.linux-amd64.tar.gz

ENV PATH=$PATH:/usr/local/go/bin
ENV GOPATH=/usr/local/go/bin

WORKDIR /usr/local/src

#CMD ["go", "version"]